# SPDX-License-Identifier: Apache-2.0

# Hardware
CONFIG_FPU=y
CONFIG_FP_HARDABI=y
CONFIG_PWM=y
CONFIG_ADC=y
CONFIG_SENSOR=y

# Shell
CONFIG_SHELL=y
CONFIG_ADC_SHELL=y
CONFIG_SENSOR_SHELL=y
CONFIG_LOG_CMDS=y

# State machine framework
CONFIG_SMF=y

# Logging
CONFIG_LOG=y
CONFIG_SHELL_LOG_BACKEND=y
CONFIG_LOG_RUNTIME_FILTERING=y
CONFIG_LOG_DEFAULT_LEVEL=4

# zbus
CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_OBSERVER_NAME=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_ZBUS_MSG_SUBSCRIBER_NET_BUF_POOL_SIZE=64
